

Const START_GAME = "Start Game"
Const NEXT_PLAYER = "Next Player"
Const BALL_DRAIN = "Ball Drain"
Const BALL_SAVE = "Ball Save"
Const GAME_OVER = "Game Over"
Const SWITCH_HIT_NODE_A = "Switch Hit Node A"
Const SWITCH_HIT_NODE_B = "Switch Hit Node B"
Const SWITCH_HIT_NODE_C = "Switch Hit Node C"
Const SWITCH_HIT_SCOOP = "Switch Hit SCOOP"
Const SWITCH_HIT_LEFT_ORBIT = "Switches Hit Left Orbit"
Const SWITCH_LEFT_FLIPPER_DOWN = "Switches Left Flipper Down"
Const SWITCH_RIGHT_FLIPPER_DOWN = "Switches Right Flipper Down"
Const SWITCH_LEFT_FLIPPER_UP = "Switches Left Flipper Up"
Const SWITCH_RIGHT_FLIPPER_UP = "Switches Right Flipper Up"
Const SWITCH_HIT_SPINNER1 = "Switches Hit Spinner 1"
Const SWITCH_HIT_SPINNER2 = "Switches Hit Spinner 2"
Const SWITCH_HIT_BUMPER = "Switches Hit Bumper"
Const SWITCH_HIT_RIGHT_RAMP = "Switches Hit Right Ramp"
Const SWITCH_HIT_LANE_A = "Switches Hit Lane A"
Const SWITCH_HIT_LEFT_RAMP = "Switches Hit Left Ramp"
Const SWITCH_HIT_RIGHT_ORBIT = "Switches Hit Right Orbit"
Const SWITCH_HIT_RAMP_LOCK = "Switch Hit Ramp Lock"

Const SWITCH_HIT_BOOST1 = "Switches Hit Boost1"
Const SWITCH_HIT_BOOST2 = "Switches Hit Boost2"
Const SWITCH_HIT_BOOST3 = "Switches Hit Boost3"

Const SWITCH_HIT_BET1 = "Switches Hit Bet 1"
Const SWITCH_HIT_BET2 = "Switches Hit Bet 2"
Const SWITCH_HIT_BET3 = "Switches Hit Bet 3"

Const SWITCH_HIT_AUGMENTATION = "Switches Hit Augmentation"
Const SWITCH_HIT_CAPTIVE = "Switches Hit Captive"
Const SWITCH_HIT_RESEARCH_1 = "Switches Hit Research 1"
Const SWITCH_HIT_RESEARCH_2 = "Switches Hit Research 2"
Const SWITCH_HIT_RESEARCH_3 = "Switches Hit Research 3"
Const SWITCH_HIT_PRE_LEFT_ORBIT = "Switches Hit Pre Left Orbit"
Const SWITCH_HIT_PRE_RIGHT_ORBIT = "Switches Hit Pre Right Orbit"


Const SWITCH_HIT_CONSOLE = "Switches Hit Console"
Const SWITCH_HIT_HYPERJUMP = "Switches Hit Hyper Jump"

Const SWITCH_HIT_LEFT_RETURN = "Switches Hit Center Ramp"
Const SWITCH_HIT_SHORTCUT = "Switches Hit Shortcut"
Const SWITCH_HIT_RAMP_PIN = "Switches Hit Ramp Pin"
Const SWITCH_HIT_PLUNGER_LANE = "Switches Hit Plunger Lane"
Const SWITCH_HIT_LIGHT_LOCK = "Switches Hit Light Lock"
Const SWITCH_HIT_LEFT_OUTLANE = "Switches Hit Left Outlane"
Const SWITCH_HIT_LEFT_INLANE = "Switches Hit Left Inlane"
Const SWITCH_HIT_RIGHT_INLANE = "Switches Hit Right Inlane"
Const SWITCH_HIT_RIGHT_OUTLANE = "Switches Hit Right Outlane"
Const SWITCH_HIT_BALL_LOCK = "Switches Hit Ball Lock"
Const SWITCH_HIT_SECRET_UPGRADE = "Switches Hit Secret Upgrade"
Const SWITCH_HIT_BET = "Switches Hit Bet"
Const SWITCH_HIT_RACE_KICKER = "Switches Hit Race Kicker"

Const SWITCHES_LAST_FLIPPER_DOWN_TIME = "Switches Last Flipper Down Time"

Const SWITCH_START_GAME_KEY = "Switches Start Game Key"
Const SWITCH_PLUNGER_KEY = "Switches Plunger Key"
Const SWITCH_SELECT_EVENT_KEY = "Switches Select Event Key"