#config_version=5
mode:
  start_events: ball_started
  priority: 2000

ball_holds:
  race_scoop:
    balls_to_hold: 1
    hold_devices: bd_race_scoop
    enable_events: race_ready
    disable_events: race_started, multiball_active
    release_one_events: race_started