#config_version=6
mode:
  start_events: start_boost_mode_actual
  stop_events: stop_boost_mode_actual
  priority: 2000

shot_profiles:
  boost_jackpot_flash:
    advance_on_hit: false
    states:
      - name: solid
        show: "off"
      - name: flashing
        show: "flash_color"
        speed: 2

shots:
  boost_grow_jackpot1:
    advance_events: advance_skillshot_left
    switch: s_sw18
    profile: boost_jackpot_flash
    show_tokens:
      lights: boost1
      color: 00FF00
  boost_grow_jackpot2:
    advance_events: advance_skillshot_middle
    switch: s_sw19
    profile: boost_jackpot_flash
    show_tokens:
      lights: boost2
      color: 00FF00
  boost_grow_jackpot3:
    advance_events: advance_skillshot_right
    switch: s_sw20
    profile: boost_jackpot_flash
    show_tokens:
      lights: boost3
      color: 00FF00
      
shot_groups:
  boost_jackpots_targets:
    shots: boost_grow_jackpot1, boost_grow_jackpot2, boost_grow_jackpot3
    rotate_left_events: timer_boost_mode_complete
    enable_events: mode_boost_started
    disable_events: mode_boost_ended

random_event_player:
  mode_boost_started:
    events:
      - advance_skillshot_left
      - advance_skillshot_middle
      - advance_skillshot_right
    

timers:
  boost_mode:
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true
    control_events:
      - event: timer_boost_mode_complete
        action: restart
      - event: boost_jackpots_targets_flashing_hit
        action: restart

sound_player:
  boost_jackpots_targets_flashing_hit:
    fx-boost:
      bus: effects

variable_player:
  boost_jackpots_targets_flashing_hit:
    score: (machine.mode_points)
